Fix syntax error in environment variable check

diff --git a/actions/instrument/deploy/action.yml b/actions/instrument/deploy/action.yml
--- a/actions/instrument/deploy/action.yml
+++ b/actions/instrument/deploy/action.yml
@@ -64,7 +64,7 @@ runs:
           key="${env%%=*}"
           value="${env#*=}"
           case "$key" in
-            OTEL_*) [ -n "$value" ] || { echo "::error::Aborting deploy because configuration variable $key is empty!"; false; }
+            OTEL_*) [ -n "$value" ] || { echo "::error::Aborting deploy because configuration variable $key is empty!"; false; } ;;
             *) ;;
           esac
         done
