Do not stop on missing dev containers

diff --git a/.github/workflows/test_shell.yaml b/.github/workflows/test_shell.yaml
--- a/.github/workflows/test_shell.yaml
+++ b/.github/workflows/test_shell.yaml
@@ -96,7 +96,14 @@ jobs:
             echo "$latest" "$name" latest
             echo "$dev" "$name" dev
           done | while read -r image os type; do
-            sudo docker pull "$image" >&2 # make sure we fail on pull if image is not available
+            sudo docker pull "$image" >&2 || image_not_found=1 # make sure we fail on pull if image is not available
+            if [ "${image_not_found:-0}" = 1 ]; then
+              if [ "$type" = dev ]; then
+                continue;
+              else
+                exit 1
+              fi
+            fi
             echo 'cat /etc/os-release | grep PRETTY >&2 && ((apt-get update && apt-get -y install /package.deb) || dnf -y install /package.rpm || yum -y install /package.rpm || zypper --non-interactive install --allow-unsigned-rpm /package.rpm || apk add --allow-untrusted /package.apk)' \
               | OTEL_SHELL_CONFIG_INJECT_DEEP=FALSE \sudo docker run --rm --network=host --mount type=bind,src="$(pwd)"/package.deb,dst=/package.deb --mount type=bind,src="$(pwd)"/package.rpm,dst=/package.rpm --mount type=bind,src="$(pwd)"/package.apk,dst=/package.apk -i "$image" >&2 \
               && echo "{\"image\":\"$image\",\"os\":\"$os\",\"type\":\"$type\"}" || true
